# Generated by Django 4.0.4 on 2026-05-15 03:16

import django.core.validators
from django.db import migrations, models
import envios.validators


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0004_alter_empleado_codigo_alter_encomienda_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomienda',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, validators=[envios.validators.validar_codigo_encomienda, django.core.validators.RegexValidator(message='El codigo solo debe contener mayusculas, numeros o guiones.', regex='^[A-Z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[envios.validators.validar_peso_positivo, django.core.validators.MinValueValidator(0.01, message='El peso minimo es 0.01 kg')]),
        ),
    ]
