# Generated by Django 4.0.4 on 2026-05-14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='codigo',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El codigo solo debe contener mayusculas, numeros o guiones.', regex='^[A-Z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='dias_entrega',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
