# Generated by Django 4.0.4 on 2026-05-14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nro_doc',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='El numero de documento solo debe contener letras y numeros.', regex='^[0-9A-Za-z]+$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El telefono solo debe contener numeros, espacios, + o -.', regex='^[0-9+\\-\\s]+$')]),
        ),
    ]
